//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\GenElectrovise\OneDrive\Desktop\Programming\RF_ASM\Crimson\CSharp\Antlr4Grammar\Crimson.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class CrimsonLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		LineComment=1, Package=2, Function=3, Global=4, Return=5, Allocate=6, 
		Structure=7, If=8, Else=9, Elif=10, Integer=11, Boolean=12, Null=13, BooleanValue=14, 
		Comparator=15, Equals=16, OpenBracket=17, CloseBracket=18, OpenSquare=19, 
		CloseSquare=20, OpenBrace=21, CloseBrace=22, Comma=23, Dot=24, SemiColon=25, 
		Underscore=26, Number=27, Identifier=28;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"LineComment", "Package", "Function", "Global", "Return", "Allocate", 
		"Structure", "If", "Else", "Elif", "Integer", "Boolean", "Null", "True", 
		"False", "BooleanValue", "Less", "Greater", "EqualTo", "Comparator", "Equals", 
		"OpenBracket", "CloseBracket", "OpenSquare", "CloseSquare", "OpenBrace", 
		"CloseBrace", "Comma", "Dot", "SemiColon", "Underscore", "Number", "Identifier", 
		"Alphabetic", "Digit", "Punctuation"
	};


	public CrimsonLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public CrimsonLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, "'package'", "'function'", "'global'", "'return'", "'allocate'", 
		"'structure'", "'if'", "'else'", "'elif'", "'int'", "'bool'", "'null'", 
		null, null, "'='", "'('", "')'", "'['", "']'", "'{'", "'}'", "','", "'.'", 
		"';'", "'_'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "LineComment", "Package", "Function", "Global", "Return", "Allocate", 
		"Structure", "If", "Else", "Elif", "Integer", "Boolean", "Null", "BooleanValue", 
		"Comparator", "Equals", "OpenBracket", "CloseBracket", "OpenSquare", "CloseSquare", 
		"OpenBrace", "CloseBrace", "Comma", "Dot", "SemiColon", "Underscore", 
		"Number", "Identifier"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Crimson.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static CrimsonLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1E', '\xF0', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x4', '%', '\t', '%', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\a', '\x2', 'P', '\n', '\x2', 
		'\f', '\x2', '\xE', '\x2', 'S', '\v', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', 
		'\x3', '\x11', '\x5', '\x11', '\xB1', '\n', '\x11', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x5', '\x15', '\xBD', 
		'\n', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', 
		'\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', 
		'\x3', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1C', '\x3', '\x1C', 
		'\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1F', 
		'\x3', '\x1F', '\x3', ' ', '\x3', ' ', '\x3', '!', '\x6', '!', '\xD6', 
		'\n', '!', '\r', '!', '\xE', '!', '\xD7', '\x3', '\"', '\x3', '\"', '\x3', 
		'\"', '\x3', '\"', '\x3', '\"', '\x3', '\"', '\a', '\"', '\xE0', '\n', 
		'\"', '\f', '\"', '\xE', '\"', '\xE3', '\v', '\"', '\x3', '\"', '\x3', 
		'\"', '\x5', '\"', '\xE7', '\n', '\"', '\x5', '\"', '\xE9', '\n', '\"', 
		'\x3', '#', '\x3', '#', '\x3', '$', '\x3', '$', '\x3', '%', '\x3', '%', 
		'\x2', '\x2', '&', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', 
		'\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', 
		'\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x2', '\x1F', 
		'\x2', '!', '\x10', '#', '\x2', '%', '\x2', '\'', '\x2', ')', '\x11', 
		'+', '\x12', '-', '\x13', '/', '\x14', '\x31', '\x15', '\x33', '\x16', 
		'\x35', '\x17', '\x37', '\x18', '\x39', '\x19', ';', '\x1A', '=', '\x1B', 
		'?', '\x1C', '\x41', '\x1D', '\x43', '\x1E', '\x45', '\x2', 'G', '\x2', 
		'I', '\x2', '\x3', '\x2', '\x6', '\x4', '\x2', '\f', '\f', '\xF', '\xF', 
		'\x4', '\x2', '\x43', '\\', '\x63', '|', '\x3', '\x2', '\x32', ';', '\x4', 
		'\x2', '\x30', '\x30', '\x61', '\x61', '\x2', '\xF2', '\x2', '\x3', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', ')', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x31', '\x3', '\x2', '\x2', '\x2', '\x2', '\x33', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x35', '\x3', '\x2', '\x2', '\x2', '\x2', '\x37', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x39', '\x3', '\x2', '\x2', '\x2', 
		'\x2', ';', '\x3', '\x2', '\x2', '\x2', '\x2', '=', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '?', '\x3', '\x2', '\x2', '\x2', '\x2', '\x41', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x43', '\x3', '\x2', '\x2', '\x2', '\x3', 'K', '\x3', 
		'\x2', '\x2', '\x2', '\x5', 'V', '\x3', '\x2', '\x2', '\x2', '\a', '^', 
		'\x3', '\x2', '\x2', '\x2', '\t', 'g', '\x3', '\x2', '\x2', '\x2', '\v', 
		'n', '\x3', '\x2', '\x2', '\x2', '\r', 'u', '\x3', '\x2', '\x2', '\x2', 
		'\xF', '~', '\x3', '\x2', '\x2', '\x2', '\x11', '\x88', '\x3', '\x2', 
		'\x2', '\x2', '\x13', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x15', '\x90', 
		'\x3', '\x2', '\x2', '\x2', '\x17', '\x95', '\x3', '\x2', '\x2', '\x2', 
		'\x19', '\x99', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x9E', '\x3', '\x2', 
		'\x2', '\x2', '\x1D', '\xA3', '\x3', '\x2', '\x2', '\x2', '\x1F', '\xA8', 
		'\x3', '\x2', '\x2', '\x2', '!', '\xB0', '\x3', '\x2', '\x2', '\x2', '#', 
		'\xB2', '\x3', '\x2', '\x2', '\x2', '%', '\xB4', '\x3', '\x2', '\x2', 
		'\x2', '\'', '\xB6', '\x3', '\x2', '\x2', '\x2', ')', '\xBC', '\x3', '\x2', 
		'\x2', '\x2', '+', '\xBE', '\x3', '\x2', '\x2', '\x2', '-', '\xC0', '\x3', 
		'\x2', '\x2', '\x2', '/', '\xC2', '\x3', '\x2', '\x2', '\x2', '\x31', 
		'\xC4', '\x3', '\x2', '\x2', '\x2', '\x33', '\xC6', '\x3', '\x2', '\x2', 
		'\x2', '\x35', '\xC8', '\x3', '\x2', '\x2', '\x2', '\x37', '\xCA', '\x3', 
		'\x2', '\x2', '\x2', '\x39', '\xCC', '\x3', '\x2', '\x2', '\x2', ';', 
		'\xCE', '\x3', '\x2', '\x2', '\x2', '=', '\xD0', '\x3', '\x2', '\x2', 
		'\x2', '?', '\xD2', '\x3', '\x2', '\x2', '\x2', '\x41', '\xD5', '\x3', 
		'\x2', '\x2', '\x2', '\x43', '\xE8', '\x3', '\x2', '\x2', '\x2', '\x45', 
		'\xEA', '\x3', '\x2', '\x2', '\x2', 'G', '\xEC', '\x3', '\x2', '\x2', 
		'\x2', 'I', '\xEE', '\x3', '\x2', '\x2', '\x2', 'K', 'L', '\a', '\x31', 
		'\x2', '\x2', 'L', 'M', '\a', '\x31', '\x2', '\x2', 'M', 'Q', '\x3', '\x2', 
		'\x2', '\x2', 'N', 'P', '\n', '\x2', '\x2', '\x2', 'O', 'N', '\x3', '\x2', 
		'\x2', '\x2', 'P', 'S', '\x3', '\x2', '\x2', '\x2', 'Q', 'O', '\x3', '\x2', 
		'\x2', '\x2', 'Q', 'R', '\x3', '\x2', '\x2', '\x2', 'R', 'T', '\x3', '\x2', 
		'\x2', '\x2', 'S', 'Q', '\x3', '\x2', '\x2', '\x2', 'T', 'U', '\b', '\x2', 
		'\x2', '\x2', 'U', '\x4', '\x3', '\x2', '\x2', '\x2', 'V', 'W', '\a', 
		'r', '\x2', '\x2', 'W', 'X', '\a', '\x63', '\x2', '\x2', 'X', 'Y', '\a', 
		'\x65', '\x2', '\x2', 'Y', 'Z', '\a', 'm', '\x2', '\x2', 'Z', '[', '\a', 
		'\x63', '\x2', '\x2', '[', '\\', '\a', 'i', '\x2', '\x2', '\\', ']', '\a', 
		'g', '\x2', '\x2', ']', '\x6', '\x3', '\x2', '\x2', '\x2', '^', '_', '\a', 
		'h', '\x2', '\x2', '_', '`', '\a', 'w', '\x2', '\x2', '`', '\x61', '\a', 
		'p', '\x2', '\x2', '\x61', '\x62', '\a', '\x65', '\x2', '\x2', '\x62', 
		'\x63', '\a', 'v', '\x2', '\x2', '\x63', '\x64', '\a', 'k', '\x2', '\x2', 
		'\x64', '\x65', '\a', 'q', '\x2', '\x2', '\x65', '\x66', '\a', 'p', '\x2', 
		'\x2', '\x66', '\b', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\a', 'i', 
		'\x2', '\x2', 'h', 'i', '\a', 'n', '\x2', '\x2', 'i', 'j', '\a', 'q', 
		'\x2', '\x2', 'j', 'k', '\a', '\x64', '\x2', '\x2', 'k', 'l', '\a', '\x63', 
		'\x2', '\x2', 'l', 'm', '\a', 'n', '\x2', '\x2', 'm', '\n', '\x3', '\x2', 
		'\x2', '\x2', 'n', 'o', '\a', 't', '\x2', '\x2', 'o', 'p', '\a', 'g', 
		'\x2', '\x2', 'p', 'q', '\a', 'v', '\x2', '\x2', 'q', 'r', '\a', 'w', 
		'\x2', '\x2', 'r', 's', '\a', 't', '\x2', '\x2', 's', 't', '\a', 'p', 
		'\x2', '\x2', 't', '\f', '\x3', '\x2', '\x2', '\x2', 'u', 'v', '\a', '\x63', 
		'\x2', '\x2', 'v', 'w', '\a', 'n', '\x2', '\x2', 'w', 'x', '\a', 'n', 
		'\x2', '\x2', 'x', 'y', '\a', 'q', '\x2', '\x2', 'y', 'z', '\a', '\x65', 
		'\x2', '\x2', 'z', '{', '\a', '\x63', '\x2', '\x2', '{', '|', '\a', 'v', 
		'\x2', '\x2', '|', '}', '\a', 'g', '\x2', '\x2', '}', '\xE', '\x3', '\x2', 
		'\x2', '\x2', '~', '\x7F', '\a', 'u', '\x2', '\x2', '\x7F', '\x80', '\a', 
		'v', '\x2', '\x2', '\x80', '\x81', '\a', 't', '\x2', '\x2', '\x81', '\x82', 
		'\a', 'w', '\x2', '\x2', '\x82', '\x83', '\a', '\x65', '\x2', '\x2', '\x83', 
		'\x84', '\a', 'v', '\x2', '\x2', '\x84', '\x85', '\a', 'w', '\x2', '\x2', 
		'\x85', '\x86', '\a', 't', '\x2', '\x2', '\x86', '\x87', '\a', 'g', '\x2', 
		'\x2', '\x87', '\x10', '\x3', '\x2', '\x2', '\x2', '\x88', '\x89', '\a', 
		'k', '\x2', '\x2', '\x89', '\x8A', '\a', 'h', '\x2', '\x2', '\x8A', '\x12', 
		'\x3', '\x2', '\x2', '\x2', '\x8B', '\x8C', '\a', 'g', '\x2', '\x2', '\x8C', 
		'\x8D', '\a', 'n', '\x2', '\x2', '\x8D', '\x8E', '\a', 'u', '\x2', '\x2', 
		'\x8E', '\x8F', '\a', 'g', '\x2', '\x2', '\x8F', '\x14', '\x3', '\x2', 
		'\x2', '\x2', '\x90', '\x91', '\a', 'g', '\x2', '\x2', '\x91', '\x92', 
		'\a', 'n', '\x2', '\x2', '\x92', '\x93', '\a', 'k', '\x2', '\x2', '\x93', 
		'\x94', '\a', 'h', '\x2', '\x2', '\x94', '\x16', '\x3', '\x2', '\x2', 
		'\x2', '\x95', '\x96', '\a', 'k', '\x2', '\x2', '\x96', '\x97', '\a', 
		'p', '\x2', '\x2', '\x97', '\x98', '\a', 'v', '\x2', '\x2', '\x98', '\x18', 
		'\x3', '\x2', '\x2', '\x2', '\x99', '\x9A', '\a', '\x64', '\x2', '\x2', 
		'\x9A', '\x9B', '\a', 'q', '\x2', '\x2', '\x9B', '\x9C', '\a', 'q', '\x2', 
		'\x2', '\x9C', '\x9D', '\a', 'n', '\x2', '\x2', '\x9D', '\x1A', '\x3', 
		'\x2', '\x2', '\x2', '\x9E', '\x9F', '\a', 'p', '\x2', '\x2', '\x9F', 
		'\xA0', '\a', 'w', '\x2', '\x2', '\xA0', '\xA1', '\a', 'n', '\x2', '\x2', 
		'\xA1', '\xA2', '\a', 'n', '\x2', '\x2', '\xA2', '\x1C', '\x3', '\x2', 
		'\x2', '\x2', '\xA3', '\xA4', '\a', 'v', '\x2', '\x2', '\xA4', '\xA5', 
		'\a', 't', '\x2', '\x2', '\xA5', '\xA6', '\a', 'w', '\x2', '\x2', '\xA6', 
		'\xA7', '\a', 'g', '\x2', '\x2', '\xA7', '\x1E', '\x3', '\x2', '\x2', 
		'\x2', '\xA8', '\xA9', '\a', 'h', '\x2', '\x2', '\xA9', '\xAA', '\a', 
		'\x63', '\x2', '\x2', '\xAA', '\xAB', '\a', 'n', '\x2', '\x2', '\xAB', 
		'\xAC', '\a', 'u', '\x2', '\x2', '\xAC', '\xAD', '\a', 'g', '\x2', '\x2', 
		'\xAD', ' ', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xB1', '\x5', '\x1D', 
		'\xF', '\x2', '\xAF', '\xB1', '\x5', '\x1F', '\x10', '\x2', '\xB0', '\xAE', 
		'\x3', '\x2', '\x2', '\x2', '\xB0', '\xAF', '\x3', '\x2', '\x2', '\x2', 
		'\xB1', '\"', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB3', '\a', '>', '\x2', 
		'\x2', '\xB3', '$', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xB5', '\a', 
		'@', '\x2', '\x2', '\xB5', '&', '\x3', '\x2', '\x2', '\x2', '\xB6', '\xB7', 
		'\a', '?', '\x2', '\x2', '\xB7', '\xB8', '\a', '?', '\x2', '\x2', '\xB8', 
		'(', '\x3', '\x2', '\x2', '\x2', '\xB9', '\xBD', '\x5', '#', '\x12', '\x2', 
		'\xBA', '\xBD', '\x5', '%', '\x13', '\x2', '\xBB', '\xBD', '\x5', '\'', 
		'\x14', '\x2', '\xBC', '\xB9', '\x3', '\x2', '\x2', '\x2', '\xBC', '\xBA', 
		'\x3', '\x2', '\x2', '\x2', '\xBC', '\xBB', '\x3', '\x2', '\x2', '\x2', 
		'\xBD', '*', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xBF', '\a', '?', '\x2', 
		'\x2', '\xBF', ',', '\x3', '\x2', '\x2', '\x2', '\xC0', '\xC1', '\a', 
		'*', '\x2', '\x2', '\xC1', '.', '\x3', '\x2', '\x2', '\x2', '\xC2', '\xC3', 
		'\a', '+', '\x2', '\x2', '\xC3', '\x30', '\x3', '\x2', '\x2', '\x2', '\xC4', 
		'\xC5', '\a', ']', '\x2', '\x2', '\xC5', '\x32', '\x3', '\x2', '\x2', 
		'\x2', '\xC6', '\xC7', '\a', '_', '\x2', '\x2', '\xC7', '\x34', '\x3', 
		'\x2', '\x2', '\x2', '\xC8', '\xC9', '\a', '}', '\x2', '\x2', '\xC9', 
		'\x36', '\x3', '\x2', '\x2', '\x2', '\xCA', '\xCB', '\a', '\x7F', '\x2', 
		'\x2', '\xCB', '\x38', '\x3', '\x2', '\x2', '\x2', '\xCC', '\xCD', '\a', 
		'.', '\x2', '\x2', '\xCD', ':', '\x3', '\x2', '\x2', '\x2', '\xCE', '\xCF', 
		'\a', '\x30', '\x2', '\x2', '\xCF', '<', '\x3', '\x2', '\x2', '\x2', '\xD0', 
		'\xD1', '\a', '=', '\x2', '\x2', '\xD1', '>', '\x3', '\x2', '\x2', '\x2', 
		'\xD2', '\xD3', '\a', '\x61', '\x2', '\x2', '\xD3', '@', '\x3', '\x2', 
		'\x2', '\x2', '\xD4', '\xD6', '\x5', 'G', '$', '\x2', '\xD5', '\xD4', 
		'\x3', '\x2', '\x2', '\x2', '\xD6', '\xD7', '\x3', '\x2', '\x2', '\x2', 
		'\xD7', '\xD5', '\x3', '\x2', '\x2', '\x2', '\xD7', '\xD8', '\x3', '\x2', 
		'\x2', '\x2', '\xD8', '\x42', '\x3', '\x2', '\x2', '\x2', '\xD9', '\xE9', 
		'\x5', '\x45', '#', '\x2', '\xDA', '\xE1', '\x5', '\x45', '#', '\x2', 
		'\xDB', '\xE0', '\x5', '\x45', '#', '\x2', '\xDC', '\xE0', '\x5', '\x41', 
		'!', '\x2', '\xDD', '\xE0', '\x5', '?', ' ', '\x2', '\xDE', '\xE0', '\x5', 
		';', '\x1E', '\x2', '\xDF', '\xDB', '\x3', '\x2', '\x2', '\x2', '\xDF', 
		'\xDC', '\x3', '\x2', '\x2', '\x2', '\xDF', '\xDD', '\x3', '\x2', '\x2', 
		'\x2', '\xDF', '\xDE', '\x3', '\x2', '\x2', '\x2', '\xE0', '\xE3', '\x3', 
		'\x2', '\x2', '\x2', '\xE1', '\xDF', '\x3', '\x2', '\x2', '\x2', '\xE1', 
		'\xE2', '\x3', '\x2', '\x2', '\x2', '\xE2', '\xE6', '\x3', '\x2', '\x2', 
		'\x2', '\xE3', '\xE1', '\x3', '\x2', '\x2', '\x2', '\xE4', '\xE7', '\x5', 
		'\x45', '#', '\x2', '\xE5', '\xE7', '\x5', '\x41', '!', '\x2', '\xE6', 
		'\xE4', '\x3', '\x2', '\x2', '\x2', '\xE6', '\xE5', '\x3', '\x2', '\x2', 
		'\x2', '\xE7', '\xE9', '\x3', '\x2', '\x2', '\x2', '\xE8', '\xD9', '\x3', 
		'\x2', '\x2', '\x2', '\xE8', '\xDA', '\x3', '\x2', '\x2', '\x2', '\xE9', 
		'\x44', '\x3', '\x2', '\x2', '\x2', '\xEA', '\xEB', '\t', '\x3', '\x2', 
		'\x2', '\xEB', '\x46', '\x3', '\x2', '\x2', '\x2', '\xEC', '\xED', '\t', 
		'\x4', '\x2', '\x2', '\xED', 'H', '\x3', '\x2', '\x2', '\x2', '\xEE', 
		'\xEF', '\t', '\x5', '\x2', '\x2', '\xEF', 'J', '\x3', '\x2', '\x2', '\x2', 
		'\v', '\x2', 'Q', '\xB0', '\xBC', '\xD7', '\xDF', '\xE1', '\xE6', '\xE8', 
		'\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
